#!/usr/bin/env node
/**
 * Automated Medusa bootstrap for local + staging.
 * Creates admin (if missing), region, sales channel, stock location, publishable API key.
 * Writes apps/mobile/.env.local with EXPO_PUBLIC_* vars for real-backend toggle.
 *
 * Prereqs: docker compose up -d && medusa running on :9000
 */
const { execSync } = require('child_process');
const fs = require('fs');
const path = require('path');
const http = require('http');

const ROOT = path.join(__dirname, '..');
const MEDUSA_DIR = path.join(ROOT, 'apps', 'medusa');
const BASE_URL = process.env.MEDUSA_URL || 'http://localhost:9000';
const ADMIN_EMAIL = process.env.SEED_ADMIN_EMAIL || 'admin@shc.local';
const ADMIN_PASS = process.env.SEED_ADMIN_PASS || 'supersecret';
const CUSTOMER_ENV_OUT = path.join(ROOT, 'apps', 'mobile-customer', '.env.local');
const COOK_ENV_OUT = path.join(ROOT, 'apps', 'mobile-cook', '.env.local');
const WEB_ENV_OUT = path.join(ROOT, 'apps', 'web', '.env.local');
const DEMO_CUSTOMER_EMAIL = process.env.SEED_CUSTOMER_EMAIL || 'customer@shc.local';
const DEMO_CUSTOMER_PASS = process.env.SEED_CUSTOMER_PASS || 'customersecret';
const ENV_EXAMPLE = path.join(ROOT, '.env.example');

function httpJson(method, urlPath, body, headers = {}) {
  return new Promise((resolve, reject) => {
    const data = body ? JSON.stringify(body) : null;
    const req = http.request(`${BASE_URL}${urlPath}`, {
      method,
      headers: {
        'Content-Type': 'application/json',
        ...(data ? { 'Content-Length': Buffer.byteLength(data) } : {}),
        ...headers,
      },
    }, (res) => {
      let raw = '';
      res.on('data', (c) => (raw += c));
      res.on('end', () => {
        let parsed = raw;
        try { parsed = JSON.parse(raw); } catch { /* text */ }
        resolve({ status: res.statusCode, body: parsed });
      });
    });
    req.on('error', reject);
    if (data) req.write(data);
    req.end();
  });
}

async function waitForServer(maxMs = 60000) {
  const start = Date.now();
  while (Date.now() - start < maxMs) {
    try {
      const res = await httpJson('GET', '/health');
      if (res.status === 200) return true;
    } catch { /* retry */ }
    await new Promise((r) => setTimeout(r, 2000));
  }
  return false;
}

async function ensureAdmin() {
  // Try login first — avoid medusa user CLI while server is running (can reset connections)
  try {
    await adminToken();
    console.log('  ✓ Admin login OK (existing user)');
    return;
  } catch { /* create below */ }
  if (process.env.SKIP_MEDUSA_USER_CLI === 'true') {
    console.log('  · Admin user create skipped (SKIP_MEDUSA_USER_CLI — create via CI/offline step)');
    return;
  }
  try {
    execSync(`pnpm exec medusa user -e ${ADMIN_EMAIL} -p ${ADMIN_PASS}`, {
      cwd: MEDUSA_DIR,
      stdio: 'pipe',
      env: { ...process.env, MEDUSA_DISABLE_ADMIN: 'true' },
    });
    console.log('  ✓ Admin user created (server was stopped for CLI)');
    await waitForServer(90000);
  } catch {
    console.log('  · Admin user create skipped — ensure admin@shc.local exists');
  }
}

async function adminToken(retries = 5) {
  let lastErr;
  for (let i = 0; i < retries; i++) {
    try {
      const res = await httpJson('POST', '/auth/user/emailpass', { email: ADMIN_EMAIL, password: ADMIN_PASS });
      if (res.status === 200 && res.body?.token) return res.body.token;
      lastErr = new Error(`Admin login failed (${res.status}): ${JSON.stringify(res.body)}`);
    } catch (e) {
      lastErr = e;
    }
    await new Promise((r) => setTimeout(r, 1500));
  }
  throw lastErr;
}

async function adminPost(token, urlPath, body) {
  return httpJson('POST', urlPath, body, { Authorization: `Bearer ${token}` });
}

async function adminGet(token, urlPath) {
  return httpJson('GET', urlPath, null, { Authorization: `Bearer ${token}` });
}

async function ensurePublishableKey(token) {
  const existing = await adminGet(token, '/admin/api-keys?type=publishable&limit=5');
  const keys = existing.body?.api_keys || existing.body?.apiKeys || [];
  const found = keys.find((k) => k.title === 'shc-mobile-publishable' && !k.revoked_at);
  if (found?.token) {
    console.log('  ✓ Reusing existing publishable key');
    return found.token;
  }
  const created = await adminPost(token, '/admin/api-keys', {
    title: 'shc-mobile-publishable',
    type: 'publishable',
  });
  if (created.status >= 200 && created.status < 300 && created.body?.api_key?.token) {
    console.log('  ✓ Created publishable API key');
    return created.body.api_key.token;
  }
  throw new Error(`Failed to create publishable key: ${JSON.stringify(created.body)}`);
}

function writeEnvFiles(pubKey) {
  const expoEnv = [
    '# Auto-generated by scripts/bootstrap-medusa.js — Medusa always required',
    `EXPO_PUBLIC_MEDUSA_BASE=${BASE_URL}`,
    `EXPO_PUBLIC_MEDUSA_PUBLISHABLE_KEY=${pubKey}`,
    '',
  ].join('\n');
  fs.writeFileSync(CUSTOMER_ENV_OUT, expoEnv);
  console.log(`  ✓ Wrote ${CUSTOMER_ENV_OUT}`);
  fs.writeFileSync(COOK_ENV_OUT, expoEnv);
  console.log(`  ✓ Wrote ${COOK_ENV_OUT}`);

  const webEnv = [
    '# Auto-generated by scripts/bootstrap-medusa.js',
    `NEXT_PUBLIC_SHC_API_BASE=${BASE_URL}`,
    `NEXT_PUBLIC_MEDUSA_PUBLISHABLE_KEY=${pubKey}`,
    '',
  ].join('\n');
  fs.writeFileSync(WEB_ENV_OUT, webEnv);
  console.log(`  ✓ Wrote ${WEB_ENV_OUT}`);

  const example = [
    '# Copy to apps/mobile-customer/.env.local after pnpm bootstrap:medusa',
    'EXPO_PUBLIC_MEDUSA_BASE=http://localhost:9000',
    'EXPO_PUBLIC_MEDUSA_PUBLISHABLE_KEY=pk_from_bootstrap',
    '',
    '# Medusa backend',
    'DATABASE_URL=postgres://shc:shc_dev@localhost:5432/shc_medusa',
    'REDIS_URL=redis://localhost:6379',
    'JWT_SECRET=change-me-in-production',
    'COOKIE_SECRET=change-me-in-production',
    'MEDUSA_DISABLE_ADMIN=true',
    '',
    '# Railway staging (set in Railway dashboard)',
    'STORE_CORS=https://your-tunnel.trycloudflare.com,http://localhost:8081',
    'ADMIN_CORS=https://your-admin.example.com',
    '',
    '# EAS preview builds',
    'EXPO_PUBLIC_MEDUSA_BASE=https://your-medusa.up.railway.app',
    '',
    '# Maestro Cloud (optional CI)',
    'MAESTRO_CLOUD_TOKEN=',
  ].join('\n');
  fs.writeFileSync(ENV_EXAMPLE, example);
  console.log(`  ✓ Wrote ${ENV_EXAMPLE}`);
}

async function ensureDemoCustomer(publishableKey) {
  let token = null;
  const reg = await httpJson('POST', '/auth/customer/emailpass/register', {
    email: DEMO_CUSTOMER_EMAIL,
    password: DEMO_CUSTOMER_PASS,
  });
  if (reg.status >= 200 && reg.status < 300 && reg.body?.token) {
    token = reg.body.token;
    console.log('  ✓ Demo customer auth registered:', DEMO_CUSTOMER_EMAIL);
  } else {
    const login = await httpJson('POST', '/auth/customer/emailpass', {
      email: DEMO_CUSTOMER_EMAIL,
      password: DEMO_CUSTOMER_PASS,
    });
    if (login.status >= 200 && login.status < 300 && login.body?.token) {
      token = login.body.token;
      console.log('  ✓ Demo customer auth login OK:', DEMO_CUSTOMER_EMAIL);
    } else {
      console.log('  · Demo customer auth setup skipped:', JSON.stringify(reg.body || login.body));
      return;
    }
  }

  const authHeaders = {
    Authorization: `Bearer ${token}`,
    'x-publishable-api-key': publishableKey,
  };
  const me = await httpJson('GET', '/store/customers/me', null, authHeaders);
  if (me.status === 200 && me.body?.customer?.id) {
    console.log('  ✓ Demo store customer profile exists:', me.body.customer.id);
    return;
  }

  const created = await httpJson(
    'POST',
    '/store/customers',
    { email: DEMO_CUSTOMER_EMAIL, first_name: 'Demo', last_name: 'Customer' },
    authHeaders
  );
  if (created.status >= 200 && created.status < 300 && created.body?.customer?.id) {
    console.log('  ✓ Demo store customer created:', created.body.customer.id);
    return;
  }
  console.log('  · Demo store customer setup skipped:', JSON.stringify(created.body || me.body));
}

async function main() {
  console.log('Singapore Home Cooks — Medusa Bootstrap (automated)\n');

  console.log('[1/6] Waiting for Medusa at', BASE_URL);
  const up = await waitForServer();
  if (!up) {
    console.error('ERROR: Medusa not reachable. Run: pnpm docker:up && pnpm medusa:dev');
    process.exit(1);
  }
  console.log('  ✓ Server healthy');

  console.log('\n[2/6] Ensuring admin user...');
  await ensureAdmin();

  console.log('\n[3/6] Admin login...');
  const token = await adminToken();
  console.log('  ✓ Authenticated');

  console.log('\n[4/6] Publishable API key...');
  const pubKey = await ensurePublishableKey(token);

  console.log('\n[5/6] Demo customer account...');
  await ensureDemoCustomer(pubKey);

  console.log('\n[6/6] Writing env files...');
  writeEnvFiles(pubKey);

  console.log('\nBootstrap complete.');
  console.log('Demo accounts:');
  console.log(`  Customer: ${DEMO_CUSTOMER_EMAIL} / ${DEMO_CUSTOMER_PASS}`);
  console.log('  Cook: rose@shc.local / cooksecret');
  console.log('Next:');
  console.log('  cd apps/medusa && pnpm seed');
  console.log('  pnpm customer:dev   # mobile customer');
  console.log('  pnpm cook:dev       # mobile cook');
  console.log('  pnpm web:dev        # web customer');
}

main().catch((e) => {
  console.error('Bootstrap failed:', e.message || e);
  process.exit(1);
});